name: Cleanup old workflows

on:
  schedule:
    - cron: '0 0 * * *' # 每天 00:00 UTC 运行
  workflow_dispatch: # 支持手动触发

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs older than 7 days
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          cutoff_date=$(date -u -d '7 days ago' +%Y-%m-%dT%H:%M:%SZ)
          echo "Deleting workflow runs older than $cutoff_date"

          # 删除所有早于 7 天的 runs
          gh api repos/${{ github.repository }}/actions/runs \
            --paginate -q '.workflow_runs[] | select(.created_at < "'$cutoff_date'") | .id' |
            while read run_id; do
              echo "Deleting run $run_id"
              gh api repos/${{ github.repository }}/actions/runs/$run_id -X DELETE
            done
