name: Cleanup old workflows

on:
  schedule:
    - cron: '0 0 * * *' # 每天 00:00 UTC 运行
  workflow_dispatch: # 允许手动触发

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        uses: cli/cli-action@v2

      - name: Keep only last 20 workflow runs
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "Keeping only the latest 20 workflow runs per workflow"

          # 遍历仓库里所有的 workflow
          gh api repos/${{ github.repository }}/actions/workflows \
            -q '.workflows[].id' | while read wf_id; do
              echo "Processing workflow $wf_id"
              
              # 获取所有 runs，跳过最新 20 条，从第 21 条开始全部删除
              gh api repos/${{ github.repository }}/actions/workflows/$wf_id/runs \
                --paginate -q '.workflow_runs[20:] | .[].id' | while read run_id; do
                  echo "Deleting run $run_id"
                  gh api repos/${{ github.repository }}/actions/runs/$run_id -X DELETE
              done
          done
